### ISSUE TITLE
MediaInfo needed for increased metadata extraction

### ISSUE THREAD

**Issue by DcR-NL** [binhex/arch-medusa#2]
I saw the ffmpeg inclusion update (thank you for that one!) and it made me look at the requirements and my own logs. Apparently Medusa includes MediaInfo binaries for the Windows and MacOS bundles but not for Linux. Can you please consider adding this "highly recommended" external dependency (if possible)?

This is from the Medusa [ReadMe.md](https://github.com/pymedusa/Medusa/blob/master/readme.md):
> Binaries for Windows and MacOS are included. Linux distributions need to manually install MediaInfo. MediaInfo is optional, but highly recommended since it increases the number of supported formats for video metadata extraction. Basic MKV metadata is supported when MediaInfo is not installed.

Log entry:
```
2017-12-18 05:03:33 WARNING  SHOWQUEUE-REFRESH :: [1a8dc66] 
=========================================================================================
MediaInfo not found on your system or could not be loaded.
Visit https://mediaarea.net/ to download it.
If you still have problems, please check if the downloaded version matches your system.
To load MediaInfo from a specific location, please define the location as follow:
  knowit --mediainfo /usr/local/mediainfo/lib <video_path>
  knowit --mediainfo /usr/local/mediainfo/bin <video_path>
  knowit --mediainfo "C:\Program Files\MediaInfo" <video_path>
  knowit --mediainfo C:\Software\MediaInfo.dll <video_path>
  knowit --mediainfo C:\Software\MediaInfo.exe <video_path>
  knowit --mediainfo /opt/mediainfo/libmediainfo.so <video_path>
  knowit --mediainfo /opt/mediainfo/libmediainfo.dylib <video_path>
=========================================================================================
```

Thank you for the consideration and for maintaining this container.

**Comment by binhex** [comment]
Done
