### ISSUE TITLE
Not working after fresh install

### ISSUE THREAD

**Issue by 3th3r** [binhex/arch-medusa#3]
Hi, 

I was trying to reinstall py medusa to correct some bug from older version.

So I duplicate my docker container, rename the previous version, rename local folder, to in a way backup my previous install of docker. 
It worked, the container have read write to data and config files.

But, from the start medusa tell me, that he has no current version and I need to update / upgrade my system. But I run the latest image of binhex/arch-medusa. And my local server is up to date, docker and docker compose to. 

So the bug is, I can't add show, I've some error with socket, and whenn I finish to add a show the add page loop to the latest show add page..... 
Some time the add show show up, but is stuck with the tempory thumbnail. 
I've done some reinstall, with latest run option, recreate manually all the folders and chown them to the correct user.
But nothing work.

So I've fallback to my backup and everything work fine. 
For me right now it's good, but for new user this would not.

My server run on the latest centOs, everthing is up to date. Medusa is behind a nginx proxy. And I've edit the local host to have a proper adress on my web browser.

**Comment by binhex** [comment]
Cannot replicate this with fresh install, possible temp issues with metadata site.
