### ISSUE TITLE
Upgrade Python version to >= 3.5

### ISSUE THREAD

**Issue by medariox** [binhex/arch-medusa#4]
Hello all! Medusa dev here ✋ 

We have noticed that your Docker image is popular! 🎉 
I'm here to inform you that we are fully Python 3 compatible since a few releases.

As you may already know Python 2.7 will reach its EOL on 01.01.2020. This means it won't be receiving any official support nor security patches anymore. For this reason we will end support for any Medusa installs using Python 2.7 on the same date.

We kindly ask you to update the Python version to >= 3.5 (preferably 3.6 or 3.7) as soon as possible. The update won't require any intervention from the end users.

Thank you for your continued support 👏

**Comment by binhex** [comment]
a quick local test and looks good to me!, commit is in and image is currently building, for ref here is the change:-

https://github.com/binhex/arch-medusa/commit/84de35abb3cc28698426db94449880e789a3f032

**Comment by medariox** [comment]
Thank you for your prompt action!
